DROP table  if exists ratings_mpa cascade;
DROP table  if exists directors cascade;
DROP table  if exists films cascade;
DROP table  if exists genres cascade;
DROP table  if exists film_genres cascade;
DROP table  if exists film_directors cascade;
DROP table  if exists users cascade;
DROP table  if exists film_likes cascade;
DROP table  if exists friends cascade;
DROP table  if exists feed cascade;
DROP table  if exists reviews cascade;
DROP table  if exists review_likes cascade;


CREATE TABLE IF NOT EXISTS ratings_mpa
(
    id          int generated by default as identity primary key,
    name        varchar(255) NOT NULL UNIQUE,
    description varchar(255) NOT NULL
    );


CREATE TABLE IF NOT EXISTS films
(
    id           bigint generated by default as identity primary key,
    name         varchar(255) NOT NULL,
    description  varchar(200),
    release_date date         NOT NULL,
    duration     int          NOT NULL,
    rating_id    int          NOT NULL REFERENCES ratings_mpa (id) ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS directors
(
    id   bigint generated by default as identity primary key,
    name varchar(255) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS genres
(
    id   bigint generated by default as identity primary key,
    name varchar(255) NOT NULL UNIQUE
    );


CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  bigint REFERENCES films (id) ON DELETE CASCADE,
    genre_id bigint REFERENCES genres (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS film_directors
(
    film_id  bigint REFERENCES films (id) ON DELETE CASCADE,
    director_id int REFERENCES directors (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
    );

CREATE TABLE IF NOT EXISTS users
(
    id       bigint generated by default as identity primary key,
    email    varchar(255) NOT NULL,
    login    varchar(255) NOT NULL,
    name     varchar(255),
    birthday date
    );

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id  bigint REFERENCES films (id) ON DELETE CASCADE,
    user_id bigint REFERENCES users (id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS friends
(
    user1 bigint REFERENCES users (id) ON DELETE CASCADE,
    user2 bigint REFERENCES users (id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS feed
(
    event_id bigint generated by default as identity primary key,
    timestamp TIMESTAMP,
    user_id int REFERENCES users(id) ON DELETE CASCADE,
    event_type varchar(255) NOT NULL,
    operation varchar(255) NOT NULL,
    entity_id int NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews
(
    id bigint generated by default as identity primary key,
    content varchar(255) NOT NULL,
    is_positive boolean NOT NULL,
    film_id  bigint REFERENCES films (id) ON DELETE CASCADE,
    user_id bigint REFERENCES users (id) ON DELETE CASCADE,
    useful bigint NOT NULL
    );

CREATE TABLE IF NOT EXISTS review_likes
(
    review_id  bigint REFERENCES reviews (id) ON DELETE CASCADE,
    user_id bigint REFERENCES users (id) ON DELETE CASCADE,
    is_like boolean NOT NULL
    );
